GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQm9iIiwiaWF0IjoxNjI4NjMxNDE2LCJleHAiOjE2Mjg2MzE0NDZ9.u8S7vScECv5yIM4zG5y7RL2cNkS0Nw7X4zXaP8HL5gk

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQm9iIiwiaWF0IjoxNjI4NjMxNDE2fQ.EVUhDtTF7Vdbe4vSlPxWHDfFUDnGcUsPShI3UmSz6i4"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQm9iIiwiaWF0IjoxNjI4NjMxNDE2fQ.EVUhDtTF7Vdbe4vSlPxWHDfFUDnGcUsPShI3UmSz6i4"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Bob"
}
